#!/usr/bin/env node
'use strict';

// Split a branch of N commits into N stacked branches (one per commit).
//
// Stacking rule: if commits C1 and C3 both touch File A, the branch for C3
// is based on the branch for C1. Commits touching disjoint files get
// independent branches (all based on base_branch).
//
// Reads Barnum task JSON from stdin.
// Writes artifacts to local_dir and emits Rebase steps to stdout.

const { execSync } = require('child_process');
const { writeFileSync, mkdirSync } = require('fs');
const { join } = require('path');
const fs = require('fs');

const GIT_ENV = { ...process.env, HUSKY: '0' };
const GIT = 'git -c core.hooksPath=/dev/null';

function run(cmd) {
  return execSync(cmd, { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'], env: GIT_ENV }).trim();
}

const input = JSON.parse(fs.readFileSync('/dev/stdin', 'utf8'));
const { local_dir } = input.value;
const PREFIX = fs.readFileSync(join(local_dir, 'prefix.txt'), 'utf8').trim();

// Compute the merge base with master — this is where the branch diverged
const base_branch = run(`${GIT} merge-base HEAD master`);

function runSafe(cmd) {
  try {
    return { ok: true, out: run(cmd) };
  } catch (e) {
    return { ok: false, out: e.stderr || e.stdout || e.message };
  }
}

// Clean working tree so checkouts don't fail
run(`${GIT} reset --hard HEAD`);

// --- Validate the merge base before splitting ---
// If the codebase doesn't pass validation at the merge base, there's no point
// splitting — every branch will inherit the same failures.
run(`${GIT} checkout ${base_branch}`);

const validateCmds = ['pnpm tsc'];
for (const cmd of validateCmds) {
  const result = runSafe(cmd);
  if (!result.ok) {
    process.stderr.write(`Merge base validation failed: ${cmd}\n${result.out}\n`);
    process.exit(1);
  }
  // Stage any changes generated by relay/changed:fix so they don't dirty the tree
  runSafe(`${GIT} reset --hard HEAD`);
}

// Check out the source branch before starting
run(`${GIT} checkout "${PREFIX}/base"`);

// Delete all existing numbered branches from previous runs
const existing = runSafe(`${GIT} branch --list "${PREFIX}/*"`);
if (existing.ok && existing.out) {
  const toDelete = existing.out.split('\n')
    .map(b => b.trim().replace(/^\* /, ''))
    .filter(b => b !== `${PREFIX}/base` && b.length > 0);
  if (toDelete.length > 0) {
    runSafe(`${GIT} branch -D ${toDelete.join(' ')}`);
  }
}

// Remember where we started so we can return
const sourceBranch = `${PREFIX}/base`;

// Get all commits on the source branch since base (oldest first)
const commitHashes = run(`${GIT} log --reverse --format=%H ${base_branch}..HEAD`)
  .split('\n')
  .filter(Boolean);

if (commitHashes.length === 0) {
  console.log(JSON.stringify([]));
  process.exit(0);
}

// Gather commit metadata
const commits = commitHashes.map(hash => ({
  hash,
  files: run(`${GIT} diff-tree --no-commit-id --name-only -r ${hash}`).split('\n').filter(Boolean),
  subject: run(`${GIT} log -1 --format=%s ${hash}`),
}));

// --- Build branches ---

// file -> most recent branch that touched it
const fileToBranch = new Map();
const branches = [];       // ordered list of branch names
const parents = {};         // branch -> parent branch (omitted if none)

for (let i = 0; i < commits.length; i++) {
  const { hash, files, subject } = commits[i];

  const branchName = `${PREFIX}/${i + 1}`;

  // Find parent: the most recent branch that shares a file with this commit
  let parentBranch = null;
  let parentIdx = -1;
  for (const file of files) {
    const prev = fileToBranch.get(file);
    if (prev) {
      const prevI = branches.indexOf(prev);
      if (prevI > parentIdx) {
        parentIdx = prevI;
        parentBranch = prev;
      }
    }
  }

  // Create the branch and cherry-pick
  const checkoutBase = parentBranch || base_branch;
  const createResult = runSafe(`${GIT} checkout -B "${branchName}" "${checkoutBase}"`);
  if (!createResult.ok) {
    process.stderr.write(`Failed to create branch ${branchName}: ${createResult.out}\n`);
    process.exit(1);
  }

  const pickResult = runSafe(`${GIT} cherry-pick ${hash}`);
  if (!pickResult.ok) {
    process.stderr.write(`Cherry-pick failed for ${hash} onto ${branchName}: ${pickResult.out}\n`);
    // Abort and bail
    runSafe(`${GIT} cherry-pick --abort`);
    run(`${GIT} checkout "${sourceBranch}"`);
    process.exit(1);
  }

  // Update tracking
  for (const file of files) {
    fileToBranch.set(file, branchName);
  }

  branches.push(branchName);
  if (parentBranch) {
    parents[branchName] = parentBranch;
  }
}

// --- Write artifacts ---

mkdirSync(local_dir, { recursive: true });

// parents.json — { branch: parent } (missing = based on base_branch)
writeFileSync(join(local_dir, 'parents.json'), JSON.stringify(parents, null, 2) + '\n');

// --- Return to source branch ---
run(`${GIT} checkout "${sourceBranch}"`);

// --- Emit Rebase steps for each branch (in order) ---
const output = branches.map(b => ({
  kind: 'Rebase',
  value: {
    branch_name: b,
    parent_branch: parents[b] || base_branch,
    local_dir,
    base_branch,
  },
}));

console.log(JSON.stringify(output));
